name: Auto Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH into VM and pull latest code
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: 34.41.135.186
          username: algross-e-commerce-website
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/YOUR_VM_USERNAME/algross_e-commerce_website
            git pull origin main
            pm2 restart all
